設計を完了させたつもり
approvers/flisan_aimless_bot pull request #1
Opened 2020-05-19 13:49 UTC by loxygenK

可能であればいっそうくんにレビューしてもらいたいです…

2020-05-19 14:19 UTC, isso0424 requested changes
設計は指摘できる気がしないのでコード周りで気になったところに***REQUEST CHANGES***するわ

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/cmds/tests/Mixed.kt
> +      description = "Prefix付きとなしを一つのオブジェクトで使用できるか確認したいんです(語彙力)"
確認用のものなら消しちゃってもいいのでは?

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   }
`NoSubCommand`が命名としてよくない気がする
`execSingleCommand`とかどうでしょ

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   }
これってここに置かなきゃダメなのか?
抽象クラスで実装されてるのがめっちゃ気になる

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      }
これコマンドが実行できるか片っ端から試してるのかな?

これだったらコマンド側で実行できる条件を指定してそれが満たされたとき実行とかの方がきれいかもしれない

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +   )
ハードコーディング警察だ!

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +      val channel = discordClient.getTextChannelById(this.loggingChannelId) ?: error("there's no such channel")
これだと失敗時にchannelにerrorが入らない?
しっかりthrowしたほうがいいかも

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +         event.message.contentDisplay.isEmpty() || event.channel.idLong != 695976154779222047
ハードコーディング警察だ!

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +
これ`{}`いらないよな?

2020-05-19 14:19 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +   fun sendHelp(event: MessageReceivedEvent) {
これ使うのchannelだけじゃね?
MessageReceivedEventで受けなくてもいい気がする

2020-05-19 14:27 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/cmds/tests/Mixed.kt
> +      description = "Prefix付きとなしを一つのオブジェクトで使用できるか確認したいんです(語彙力)"
これを消すと下の`screamWithPrefix`が動かなくなってしまいます…

2020-05-19 14:27 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +   )
こマ？newHarachoみたいに設定ファイルから参照できるべきですか？

2020-05-19 14:37 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +
ああああああああああああああああああああああああ！！！！！！！！！！！！！！！！！！！！！

2020-05-20 06:40 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   }
継承したクラスでいちいち実装しなくてもヘルプがだせるようにしたんだけど…ここに置くのはまずいですか…？

2020-05-20 06:47 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   }
ああこれコマンドごとのヘルプのテンプレか

じゃあこれでいいや（）

2020-05-20 07:48 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   }
そそ
:bow:

2020-05-20 07:48 UTC, loxygenK commented
やってみたんですけどうーんこのって感じになってる気がします(なってる)
お世話になります:bow:

2020-05-25 00:05 UTC, isso0424 requested changes

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      }
どうしてもこれが気になるのでアドバイスします(宣言)

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      for (command in COMMAND_EXECUTORS) {
`コマンドを実行するもの`が`コマンド`に対してぶち込まれてるのが超気になる
正直このlistはCOMMANDSの方が直感的

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +         throw IllegalArgumentException("そのメインコマンドはうちの子じゃありません")
`isApplicable`で判定してるのに2回も判定しなくていい

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      }
まず、47〜50行目はif文に全部ぶち込むんじゃなくて一回意味変数`allowExec`とかにぶち込んだほうが読みやすくなる

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +            event.message.contentDisplay
パット見わかりづらいので`getQuery`とか`findQuery`とかに分けてしまおう

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +            ) else event.message.contentDisplay,
こんな感じにつながるととても読みづらいお気持ち
関数の引数に三項演算子を与えたり関数を与えたりするのは控えて意味変数に括りだそう

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +            event.message.contentDisplay
ここで`String?`を返すことで`fetchSubCommandMethodToRun`の段階でnullチェック入れて早期リターンさせれるようになる

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +   private fun fetchSubCommandMethodToRun(query: String, argCount: Int, hasPrefix: Boolean): Method? {
`fetchPrefixfulCommandMethodToRun`の第一引数がidentifyなのにこっちの第一引数がqueryなのめっちゃ気になる

どっちかに統一したほうがコードの流れがわかりやすくなる

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/CommandExecutor.kt
> +         if (method.second.identify != identify) continue
```suggestion
val found: Boolean = this.prefixfulMethodCache.filter {it.second.identify == identify}.isNotEmpty()
if (found)
```

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +         }
ログかなんか出そう

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      }
52行目は設計次第でdoesHasPrefix渡さなくて済みます

2020-05-25 00:05 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      for (executor in COMMAND_EXECUTORS) {
commandなのかexecutorなのかはっきりしろ

2020-05-29 09:32 UTC, loxygenK commented
うぅん…うぅん…
自分のコードに自信を持つことができません
対戦よろしくおねがいします

2020-05-29 11:00 UTC, mirror-kt requested changes
設計はまぁまぁとりあえずめちゃくちゃやばいとこはないのでよしとして、Kotlin的な書き方になるようにRequestChangesしときます。

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/Main.kt
> +   val settingFile = File("settings.json")
Fileは古いAPIなのでなるべく使わないほうが嬉しくなれます。
FilesクラスとかPathクラスについて調べてみてください。

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/cmds/tests/Ping.kt
> +   @Argument(count = 1, denyLess = false)
denyLess、requiredとかに名前変えませんか
```suggestion
   @Argument(count = 1, required = false)
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/cmds/tests/Ping.kt
> +
安易にvarにしないでください
```suggestion
      val pingMillisec = args.getOrNull(0)?.toIntOrNull() ?: Random.nextInt(10, 300000)
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/client/Client.kt
> +      discordClient = jdaBuilder.build()
メソッドチェーンするかapply使いませんか
```suggestion
      discordClient = JDABuilder.createDefault(token)
      	.setActivity(Activity.of(Activity.ActivityType.DEFAULT, "hennlo world"))
      	.addEventListeners(Client)
      	.build()
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/client/Client.kt
> +   private var loggingChannelId: Long = -1
Delegates.nonNull()を使うべき

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/client/Client.kt
> +      if ((event.author.isBot && !userIdsWhiteList.contains(event.author.idLong)) ||
`contains` は `in` が演算子オーバーロードしています。
```suggestion
      if ((event.author.isBot && event.author.idLong !in userIdsWhiteList) ||
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/client/Client.kt
> +         event.message.contentDisplay.isEmpty() || event.channel.idLong != loggingChannelId
いっぺんに処理しすぎでは
おとなしくifを複数書きましょう

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      val doesHasPrefix = event.message.contentDisplay.startsWith(PREFIX)
```suggestion
      val doesHavePrefix = event.message.contentDisplay.startsWith(PREFIX)
```
英文法カスカスカス

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      val rawText = event.message.contentDisplay.substring(if (doesHasPrefix) PREFIX.length else 0)
```suggestion
      val rawText = event.message.contentDisplay.let { if(doesHavePrefix) it.substring(PREFIX.length) else it }
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      if (doesHasPrefix && content[0] == "help") {
OutOfRangeでるぞこれ

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      }
安易にvarにするな
```suggestion
      val result: CommandResult = COMMANDS.find { it.isApplicable(if(doesHavePrefix) content[0] else event.message.contentDisplay) }
      	?.runCommand(content, event)
      	?: CommandResult.UNKNOWN_MAIN_COMMAND
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      helpText += "各コマンドの詳細は`//<command.name>`を叩くと表示されます"
buildStringっていう関数があるのでもうちょっときれいに書けると思ふ

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/ABCCommandExecutor.kt
> +abstract class ABCCommandExecutor {
命名がカス
ExecutorじゃないだろExecuteされる側やん
あとKotlinではABCという接頭辞は使わないことが多いので
`AbstractCommand` とかにしませんか

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/ABCCommandExecutor.kt
> +   abstract fun executeCommand(content: List<String>, event: MessageReceivedEvent): CommandResult
内部呼び出し用ならprotectedつけませんか
```suggestion
   abstract protected fun executeCommand(content: List<String>, event: MessageReceivedEvent): CommandResult
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommandExecutor.kt
> +abstract class PrefixlessCommandExecutor : ABCCommandExecutor() {
上に同じ
Executorではないだろう

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommandExecutor.kt
> +      prefixlessMethodCache = prefixlessMethods.toList()
Kotlinのクラスに対してJavaのリフレクションをごにょごにょすると実はつらいことが起きることがあるのでできる限りKotlinのリフレクションを使って欲しい気持ち

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommandExecutor.kt
> +      return this.prefixlessMethodCache.find { Regex(it.second.triggerRegex).containsMatchIn(query) } != null
```suggestion
      return this.prefixlessMethodCache.any { Regex(it.second.triggerRegex).containsMatchIn(query) }
```

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommandExecutor.kt
> +      prefixlessMethodCache = prefixlessMethods.toList()
あと引数までチェックしないと実行時例外起こすぞ

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommandExecutor.kt
> +abstract class PrefixnessCommandExecutor(
Executorではない(ry

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommandExecutor.kt
> +   }
PrefixCommandの方も参照

2020-05-29 11:00 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/annotations/PrefixlessCommand.kt
> +    val triggerRegex: String
これRegexを受け取ったほうがいいんじゃないの

2020-05-29 11:03 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/cmds/tests/Ping.kt
> +   @Argument(count = 1, denyLess = false)
あ、ガバじゃんこれ
引数の数が少ないことを許容するかどうかか

2020-05-29 12:42 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      if (doesHasPrefix && content[0] == "help") {
空文字が`split`に与えられた場合は、空文字が入った配列が返却されるみたいです(`[""]`)
なのでたぶん`OutOfRange`は大丈夫そうですが、やっぱり気持ち悪いですかね…？

2020-05-29 12:52 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      if (doesHasPrefix && content[0] == "help") {
ほんまか？
[こう](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjcwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbmZ1biBtYWluKCkge1xuICAgIHByaW50bG4oXCJcIi5zcGxpdChcIiBcIikpXG59In0=)なったが

2020-05-29 15:57 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/annotations/PrefixlessCommand.kt
> +    val triggerRegex: String
annotationのパラメータには`Regex`は指定できないみたいです…

2020-05-29 16:14 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/Client.kt
> +      val channel = discordClient.getTextChannelById(this.loggingChannelId) ?: error("there's no such channel")
error()の戻り値はNothingなのでその心配はない
errorは内部でIllegalStateExceptionかなんかをthrowするだけの関数

2020-05-29 16:15 UTC, mirror-kt commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/annotations/PrefixlessCommand.kt
> +    val triggerRegex: String
あーそっか静的に解決できる奴だけだな…
じゃあStringかぁ

2020-05-29 16:29 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +      if (doesHasPrefix && content[0] == "help") {
空文字列で中身が見えなくて、空配列に見えてるんだと思います(`size`は`1`で、`[0]`でもアクセスできました)
https://pl.kotl.in/8heiqLW5j

2020-05-29 16:59 UTC, loxygenK commented
レビューありがとうございます！！！！！！！！！！
とりあえず教えに従ってみました

2020-06-01 00:55 UTC, mirror-kt approved these changes

2020-06-03 09:31 UTC, isso0424 reviewed
宗教が入るかもしらんので***†Comment†***

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/AbstractCommand.kt
> +         println("Stacktrace:")
標準出力にエラー出してほしくない?

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +         }
`command failed: Invalid arguments`とか`command failed: unknown`とかみたいな標準出力しても良いかも知らん

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommand.kt
> +         return method.first
```suggestion
         if (Regex(method.second.triggerRegex).containsMatchIn(content)) return method.first
```
2重否定してまで`continue`するの気持ち悪くない?

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommand.kt
> +   open fun execSingleCommand(args: List<String>, event: MessageReceivedEvent): CommandResult {
どっから呼ばれるんだ...?

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommand.kt
> +         delete(length - 3, length)
このdelete使わなくてもよくね?

2020-06-03 09:31 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommand.kt
> +         prefixfulMethods.add(Pair(callable as KCallable<CommandResult>, commandAnt))
continue要らんくない?

2020-06-03 11:12 UTC, loxygenK commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommand.kt
> +         return method.first
`find` メソッド使ったら最強じゃね？と思ったので`find`を使いました
kotlinめっちゃすきかもしれん

2020-06-03 11:36 UTC, isso0424 reviewed
ガバってますぜ

2020-06-03 11:36 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/CommandManager.kt
> +         delete(length - 3, length)
PLEASE DELETE DELETE

2020-06-03 11:36 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixlessCommand.kt
> +         if (!(callable.parameters.map { it.type } contentEquals expectedParamTypes)) continue
これ反転消してcontinue消そうぜ

2020-06-03 11:37 UTC, loxygenK commented
ﾋﾟｩｨｨｨｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲｲwwwwwwwwwwwwwwwwwwwwwwwww(ガバに気づいて辱めで指が蒸発する音)

2020-06-03 14:50 UTC, isso0424 requested changes

2020-06-03 14:50 UTC, isso0424 commented on src/main/kotlin/io/github/loxygen/aimlessbot/lib/commands/abc/PrefixnessCommand.kt
> +   val subCommandContent = content.subList(1, content.size)
インデントがばってますよ

2020-06-03 15:02 UTC, isso0424 approved these changes

2020-06-04 06:29 UTC, loxygenK commented
A゛p゛p゛r゛o゛v゛e゛お゛い゛し゛い゛
レビューありがとうございました！！！！！！！！！！！！！！１１１

2020-06-04 06:29 UTC, merged